### ISSUE TITLE
KeyError: 'products' when trying to access ingredients

### ISSUE THREAD

**Issue by itsmemala** [openfoodfacts/openfoodfacts-python#81] opened 2022-03-05 18:26 UTC
Hi,

I'm trying to access ingredients using the line:
openfoodfacts.facets.get_ingredients()

However, I get the error:
KeyError: 'products'

What could be the causes of this error?

Do I need an account to be able to access the ingredients? I created an account and tried to login using this line:
login_session_object = openfoodfacts.utils.login_into_OFF()

It says mismatched username and passoword - but I'm sure that I've typed them correctly.

I'm using python 3.8.8 and Jupyter notebook.

**Comment by teolemon** [comment] 2022-03-05 21:18
nope, no account needed, it might be related to an API change, possibly

**Comment by MahmoudHamdy02** [comment] 2022-03-09 14:23
I have tried downloading the code and importing the module locally, and `get_ingredients` works normally.
![image](https://user-images.githubusercontent.com/90795679/157460514-0d99013b-a928-4446-aa21-d6e2909712c9.png)

**Comment by MahmoudHamdy02** [comment] 2022-03-09 18:00
It seems that the issue is coming from this if statement
![image](https://user-images.githubusercontent.com/90795679/157502227-84860d46-878e-4784-b2a4-2c36519985ba.png)
When it is commented out, it works normally,  however this `__init__.py` file (in python's installed modules folder) is not the same as the file in this repo.

**Comment by teolemon** [comment] 2022-03-11 17:32
@MahmoudHamdy02 I believe the PyPi version is very old. I've opened a PR to allow automated publication. Meanwhile, we need to fix this

**Comment by itsmemala** [comment] 2022-03-24 16:27
Hi,

I have been able to get it to work after downloading and importing the module locally. However, it seems to return exactly 10000 ingredients - is this the full list of ingredients or is this a limit of the function?

**Comment by MahmoudHamdy02** [comment] 2022-03-24 17:20
I have tried looking the code and this how I think it works.

If you use the python module (e.g. `get_packaging()`) it grabs the data from the website through a link, (`https://world.openfoodfacts.org/packaging.json` in this case). I have tried downloading the data manually from the browser and it was also 10000 rows, so the issue is that the website API/backend only returns 10000 rows in the response.

**Comment by itsmemala** [comment] 2022-03-24 17:23
Ah I see, I expected that. Is there any way to modify the python module to extract all ingredients?

**Comment by MahmoudHamdy02** [comment] 2022-03-24 17:26
I suspect the issue is coming from the python folksonomy API not the python module, but I'm still looking into it though.

**Comment by aadarsh-ram** [comment] 2022-04-08 07:25
@itsmemala The issue arised due to a old release stuck in PyPI. With PR #88, a new release (0.1.3) has been published to PyPI which solves this issue. Please do close this issue after verification.

**Closed as completed** 2022-04-10 10:01 UTC
Labels: 🐛 bug, 🥗 ingredients
